import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { IMAGES } from "../lib/images";

const prisma = new PrismaClient();

async function main() {
  const email = (process.env.ADMIN_EMAIL ?? "admin@toraetmangal.com").toLowerCase();
  const password = process.env.ADMIN_PASSWORD ?? "ChangeThisPassword123";
  const name = process.env.ADMIN_NAME ?? "TORA ET Yönetim";

  await prisma.user.upsert({
    where: { email },
    update: {
      name,
      role: "ADMIN",
      passwordHash: await bcrypt.hash(password, 12),
    },
    create: {
      email,
      name,
      role: "ADMIN",
      passwordHash: await bcrypt.hash(password, 12),
    },
  });

  const categoryData = [
    { name: "Izgaralar", slug: "izgaralar", sortOrder: 1 },
    { name: "Kebaplar", slug: "kebaplar", sortOrder: 2 },
    { name: "Steakler", slug: "steakler", sortOrder: 3 },
    { name: "Pideler", slug: "pideler", sortOrder: 4 },
    { name: "Yan Lezzetler", slug: "yan-lezzetler", sortOrder: 5 },
    { name: "Salatalar", slug: "salatalar", sortOrder: 6 },
    { name: "Tatlılar", slug: "tatlilar", sortOrder: 7 },
    { name: "İçecekler", slug: "icecekler", sortOrder: 8 },
  ];

  const categories = [];
  for (const category of categoryData) {
    categories.push(
      await prisma.category.upsert({
        where: { slug: category.slug },
        update: category,
        create: category,
      }),
    );
  }
  const cat = Object.fromEntries(categories.map((item) => [item.slug, item.id]));

  const products = [
    {
      name: "TORA ET KARIŞIK IZGARA",
      slug: "tora-et-karisik-izgara",
      description: "Dana antrikot, kuzu pirzola, adana kebap, sucuk ve kanat.",
      ingredients: "Dana antrikot, kuzu pirzola, adana kebap, sucuk, tavuk kanat, közlenmiş biber, domates",
      allergens: "Gluten (marinasyon)",
      price: 650,
      image: IMAGES.food.karisikIzgara,
      categoryId: cat.izgaralar,
      isFeatured: true,
      hasDoneness: true,
      sortOrder: 1,
    },
    {
      name: "Sucuk Izgara",
      slug: "sucuk-izgara",
      description: "Mangalda közlenmiş, bol baharatlı el yapımı sucuk.",
      ingredients: "Dana sucuk, kırmızı biber",
      allergens: "",
      price: 280,
      image: IMAGES.food.sucuk,
      categoryId: cat.izgaralar,
      sortOrder: 2,
    },
    {
      name: "Tavuk Kanat",
      slug: "tavuk-kanat",
      description: "Özel sosunda dinlendirilmiş, közde çıtır kanat.",
      ingredients: "Tavuk kanat, pul biber, yoğurt marinad",
      allergens: "Süt",
      price: 320,
      image: IMAGES.food.kanat,
      categoryId: cat.izgaralar,
      sortOrder: 3,
    },
    {
      name: "Köfte",
      slug: "kofte",
      description: "El yapımı dana köfte, közde pişirilir.",
      ingredients: "Dana kıyma, soğan, baharat",
      allergens: "Gluten",
      price: 340,
      image: IMAGES.food.kofte,
      categoryId: cat.izgaralar,
      sortOrder: 4,
    },
    {
      name: "Kuzu Kaburga",
      slug: "kuzu-kaburga",
      description: "Yavaş pişirilmiş, kemikli kuzu kaburga.",
      ingredients: "Kuzu kaburga, tuz, kekik",
      allergens: "",
      price: 620,
      image: IMAGES.food.kuzuPirzola,
      categoryId: cat.izgaralar,
      sortOrder: 5,
    },
    {
      name: "Adana Kebap",
      slug: "adana-kebap",
      description: "Acılı, zırh kıyması ile hazırlanan klasik Adana.",
      ingredients: "Dana-kuzu kıyma, kırmızı biber, kuyruk yağı",
      allergens: "",
      price: 390,
      image: IMAGES.food.adana,
      categoryId: cat.kebaplar,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      name: "Urfa Kebap",
      slug: "urfa-kebap",
      description: "Acısız, yoğun et aromalı Urfa kebap.",
      ingredients: "Dana-kuzu kıyma, isot, kuyruk yağı",
      allergens: "",
      price: 390,
      image: IMAGES.food.urfa,
      categoryId: cat.kebaplar,
      sortOrder: 2,
    },
    {
      name: "Kuzu Şiş",
      slug: "kuzu-sis",
      description: "Marine kuzu kuşbaşı, közde şiş.",
      ingredients: "Kuzu but, zeytinyağı, kekik",
      allergens: "",
      price: 480,
      image: IMAGES.food.kuzuSis,
      categoryId: cat.kebaplar,
      sortOrder: 3,
    },
    {
      name: "Tavuk Şiş",
      slug: "tavuk-sis",
      description: "Yoğurt marinadında tavuk şiş.",
      ingredients: "Tavuk göğüs, yoğurt, sarımsak",
      allergens: "Süt",
      price: 310,
      image: IMAGES.food.tavukSis,
      categoryId: cat.kebaplar,
      sortOrder: 4,
    },
    {
      name: "Beyti Kebap",
      slug: "beyti-kebap",
      description: "Lavaşta, tereyağlı ve yoğurtlu beyti.",
      ingredients: "Kıyma, lavaş, yoğurt, tereyağı, domates sos",
      allergens: "Gluten, süt",
      price: 420,
      image: IMAGES.food.beyti,
      categoryId: cat.kebaplar,
      sortOrder: 5,
    },
    {
      name: "Ciğer Şiş",
      slug: "ciger-sis",
      description: "Taze kuzu ciğeri, sumaklı soğan ile.",
      ingredients: "Kuzu ciğer, isot, soğan",
      allergens: "",
      price: 360,
      image: IMAGES.food.ciger,
      categoryId: cat.kebaplar,
      sortOrder: 6,
    },
    {
      name: "Dana Antrikot",
      slug: "dana-antrikot",
      description: "Kuru dinlendirilmiş dana antrikot, mangalda mühürlenir.",
      ingredients: "Dana antrikot, deniz tuzu, tereyağı",
      allergens: "Süt",
      price: 650,
      image: IMAGES.food.danaAntrikot,
      categoryId: cat.steakler,
      isFeatured: true,
      hasDoneness: true,
      sortOrder: 1,
    },
    {
      name: "Kuzu Pirzola",
      slug: "kuzu-pirzola",
      description: "Köz ateşinde pişmiş, kemikli kuzu pirzola.",
      ingredients: "Kuzu pirzola, biberiye, zeytinyağı",
      allergens: "",
      price: 720,
      image: IMAGES.food.kuzuPirzola,
      categoryId: cat.steakler,
      isFeatured: true,
      hasDoneness: true,
      sortOrder: 2,
    },
    {
      name: "T-Bone Steak",
      slug: "t-bone-steak",
      description: "Antrikot ve kontrfile bir arada, kalın kesim T-Bone.",
      ingredients: "Dana T-Bone, tuz, karabiber",
      allergens: "",
      price: 890,
      image: IMAGES.food.tbone,
      categoryId: cat.steakler,
      hasDoneness: true,
      sortOrder: 3,
    },
    {
      name: "Ribeye",
      slug: "ribeye",
      description: "Mermer damarlı ribeye, tereyağında dinlendirilir.",
      ingredients: "Dana ribeye, kekik, tereyağı",
      allergens: "Süt",
      price: 840,
      image: IMAGES.food.ribeye,
      categoryId: cat.steakler,
      hasDoneness: true,
      sortOrder: 4,
    },
    {
      name: "Bonfile",
      slug: "bonfile",
      description: "Yumuşak dana bonfile, şef usulü pişirme.",
      ingredients: "Dana bonfile, deniz tuzu",
      allergens: "",
      price: 920,
      image: IMAGES.food.bonfile,
      categoryId: cat.steakler,
      hasDoneness: true,
      sortOrder: 5,
    },
    {
      name: "Kıymalı Pide",
      slug: "kiymali-pide",
      description: "Taş fırında kıymalı klasik pide.",
      ingredients: "Hamur, dana kıyma, soğan, biber",
      allergens: "Gluten",
      price: 240,
      image: IMAGES.food.pideKiymali,
      categoryId: cat.pideler,
      sortOrder: 1,
    },
    {
      name: "Kaşarlı Pide",
      slug: "kasarli-pide",
      description: "Bol kaşarlı, fırından çıtır pide.",
      ingredients: "Hamur, kaşar peyniri",
      allergens: "Gluten, süt",
      price: 230,
      image: IMAGES.food.pideKasarli,
      categoryId: cat.pideler,
      sortOrder: 2,
    },
    {
      name: "Karışık Pide",
      slug: "karisik-pide",
      description: "Kıyma, kaşar ve sucuklu karışık pide.",
      ingredients: "Hamur, kıyma, kaşar, sucuk",
      allergens: "Gluten, süt",
      price: 270,
      image: IMAGES.food.pideKiymali,
      categoryId: cat.pideler,
      sortOrder: 3,
    },
    {
      name: "Lahmacun",
      slug: "lahmacun",
      description: "İnce hamur, bol kıymalı Antep usulü.",
      ingredients: "Hamur, kıyma, domates, biber, maydanoz",
      allergens: "Gluten",
      price: 90,
      image: IMAGES.food.lahmacun,
      categoryId: cat.pideler,
      sortOrder: 4,
    },
    {
      name: "Patates Kızartması",
      slug: "patates-kizartmasi",
      description: "El kesimi, çıtır patates.",
      ingredients: "Patates, deniz tuzu",
      allergens: "",
      price: 90,
      image: IMAGES.food.patates,
      categoryId: cat["yan-lezzetler"],
      sortOrder: 1,
    },
    {
      name: "Haydari",
      slug: "haydari",
      description: "Süzme yoğurt, sarımsak ve nane.",
      ingredients: "Süzme yoğurt, sarımsak, nane",
      allergens: "Süt",
      price: 80,
      image: IMAGES.food.haydari,
      categoryId: cat["yan-lezzetler"],
      sortOrder: 2,
    },
    {
      name: "Ezme",
      slug: "ezme",
      description: "Acılı, taze baharatlı ezme.",
      ingredients: "Domates, biber, soğan, nar ekşisi",
      allergens: "",
      price: 80,
      image: IMAGES.food.ezme,
      categoryId: cat["yan-lezzetler"],
      sortOrder: 3,
    },
    {
      name: "Cacık",
      slug: "cacik",
      description: "Nane ve salatalıklı cacık.",
      ingredients: "Yoğurt, salatalık, nane, sarımsak",
      allergens: "Süt",
      price: 70,
      image: IMAGES.food.cacik,
      categoryId: cat["yan-lezzetler"],
      sortOrder: 4,
    },
    {
      name: "Çoban Salata",
      slug: "coban-salata",
      description: "Domates, salatalık, biber ve soğan.",
      ingredients: "Domates, salatalık, biber, soğan, zeytinyağı",
      allergens: "",
      price: 110,
      image: IMAGES.food.coban,
      categoryId: cat.salatalar,
      sortOrder: 1,
    },
    {
      name: "Mevsim Salata",
      slug: "mevsim-salata",
      description: "Günün taze yeşillikleri ve nar ekşisi.",
      ingredients: "Mevsim yeşillikleri, zeytinyağı, nar ekşisi",
      allergens: "",
      price: 120,
      image: IMAGES.food.mevsim,
      categoryId: cat.salatalar,
      sortOrder: 2,
    },
    {
      name: "Künefe",
      slug: "kunefe",
      description: "Antep fıstıklı, sıcak künefe.",
      ingredients: "Kadayıf, peynir, şerbet, Antep fıstığı",
      allergens: "Gluten, süt, antep fıstığı",
      price: 180,
      image: IMAGES.food.kunefe,
      categoryId: cat.tatlilar,
      sortOrder: 1,
    },
    {
      name: "Katmer",
      slug: "katmer",
      description: "Antep usulü fıstıklı katmer.",
      ingredients: "Yufka, kaymak, Antep fıstığı",
      allergens: "Gluten, süt, antep fıstığı",
      price: 190,
      image: IMAGES.food.katmer,
      categoryId: cat.tatlilar,
      sortOrder: 2,
    },
    {
      name: "Baklava",
      slug: "baklava",
      description: "Cevizli ve fıstıklı baklava dilimi.",
      ingredients: "Yufka, ceviz, fıstık, şerbet",
      allergens: "Gluten, ceviz, antep fıstığı",
      price: 160,
      image: IMAGES.food.baklava,
      categoryId: cat.tatlilar,
      sortOrder: 3,
    },
    {
      name: "Sütlaç",
      slug: "sutlac",
      description: "Fırın sütlaç, tarçın ile.",
      ingredients: "Süt, pirinç, şeker, tarçın",
      allergens: "Süt",
      price: 110,
      image: IMAGES.food.sutlac,
      categoryId: cat.tatlilar,
      sortOrder: 4,
    },
    {
      name: "Ayran",
      slug: "ayran",
      description: "Ev yapımı, köpüklü ayran.",
      ingredients: "Yoğurt, su, tuz",
      allergens: "Süt",
      price: 40,
      image: IMAGES.food.ayran,
      categoryId: cat.icecekler,
      sortOrder: 1,
    },
    {
      name: "Kola",
      slug: "kola",
      description: "Soğuk kola.",
      ingredients: "",
      allergens: "",
      price: 50,
      image: IMAGES.food.kola,
      categoryId: cat.icecekler,
      sortOrder: 2,
    },
    {
      name: "Şalgam",
      slug: "salgam",
      description: "Acılı veya acısız şalgam.",
      ingredients: "Şalgam suyu",
      allergens: "",
      price: 45,
      image: IMAGES.food.salgam,
      categoryId: cat.icecekler,
      sortOrder: 3,
    },
    {
      name: "Türk Kahvesi",
      slug: "turk-kahvesi",
      description: "Közde pişmiş Türk kahvesi.",
      ingredients: "Türk kahvesi",
      allergens: "",
      price: 60,
      image: IMAGES.food.kahve,
      categoryId: cat.icecekler,
      sortOrder: 4,
    },
    {
      name: "Çay",
      slug: "cay",
      description: "Taze demlenmiş çay.",
      ingredients: "Siyah çay",
      allergens: "",
      price: 25,
      image: IMAGES.food.cay,
      categoryId: cat.icecekler,
      sortOrder: 5,
    },
    {
      name: "Şişe Su",
      slug: "sise-su",
      description: "Doğal kaynak suyu.",
      ingredients: "",
      allergens: "",
      price: 20,
      image: IMAGES.food.su,
      categoryId: cat.icecekler,
      sortOrder: 6,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: { ...product, isAvailable: true },
    });
  }

  for (let number = 1; number <= 20; number += 1) {
    await prisma.table.upsert({
      where: { number },
      update: { isActive: true },
      create: {
        number,
        qrToken: `tora-masa-${number}-${crypto.randomUUID().slice(0, 8)}`,
        isActive: true,
      },
    });
  }

  await prisma.orderSequence.upsert({
    where: { id: "default" },
    update: {},
    create: { id: "default", year: new Date().getFullYear(), sequence: 44 },
  });

  await prisma.restaurantSettings.upsert({
    where: { id: "default" },
    update: {},
    create: {
      id: "default",
      name: "TORA ET MANGAL",
      phone: process.env.NEXT_PUBLIC_RESTAURANT_PHONE ?? "+905551112233",
      whatsapp: process.env.NEXT_PUBLIC_WHATSAPP ?? "905551112233",
      address: "TORA ET MANGAL, İstanbul",
      instagram: process.env.NEXT_PUBLIC_INSTAGRAM ?? "https://instagram.com/toraetmangal",
      facebook: "",
      workingHours: JSON.stringify({
        weekdays: "11:00 – 00:00",
        weekend: "11:00 – 01:00",
      }),
      googleMapsUrl: process.env.NEXT_PUBLIC_GOOGLE_MAPS_URL ?? "https://maps.google.com/?q=Istanbul",
      logo: "/images/logo/logo.png",
      homepageTagline:
        "En taze etler, özgün tarifler ve mangalın en lezzetli hali TORA ET MANGAL'da.",
      aboutText:
        "TORA ET MANGAL, seçkin etleri çiftlikten soframıza taşıyan bir mangal ve steakhouse kültürüdür. Doğal beslenmiş hayvanlardan gelen etler, usta ellerde köz ateşiyle buluşur. Aile sofraları, dost meclisleri ve özel günler için sakin, sıcak ve kaliteli bir atmosfer sunarız.",
    },
  });

  console.log("Seed completed.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
